/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const ProfileIndexLazyImport = createFileRoute('/profile/')()
const GoalsIndexLazyImport = createFileRoute('/goals/')()
const ExercisesIndexLazyImport = createFileRoute('/exercises/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProfileIndexLazyRoute = ProfileIndexLazyImport.update({
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile/index.lazy').then((d) => d.Route))

const GoalsIndexLazyRoute = GoalsIndexLazyImport.update({
  path: '/goals/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/goals/index.lazy').then((d) => d.Route))

const ExercisesIndexLazyRoute = ExercisesIndexLazyImport.update({
  path: '/exercises/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exercises/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/exercises/': {
      preLoaderRoute: typeof ExercisesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/goals/': {
      preLoaderRoute: typeof GoalsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      preLoaderRoute: typeof ProfileIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  ExercisesIndexLazyRoute,
  GoalsIndexLazyRoute,
  ProfileIndexLazyRoute,
])

/* prettier-ignore-end */
