/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ProfileIndexLazyImport = createFileRoute('/profile/')()
const IndexIndexLazyImport = createFileRoute('/index/')()
const ExercisesIndexLazyImport = createFileRoute('/exercises/')()

// Create/Update Routes

const ProfileIndexLazyRoute = ProfileIndexLazyImport.update({
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile/index.lazy').then((d) => d.Route))

const IndexIndexLazyRoute = IndexIndexLazyImport.update({
  path: '/index/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index/index.lazy').then((d) => d.Route))

const ExercisesIndexLazyRoute = ExercisesIndexLazyImport.update({
  path: '/exercises/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exercises/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/exercises/': {
      preLoaderRoute: typeof ExercisesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/index/': {
      preLoaderRoute: typeof IndexIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      preLoaderRoute: typeof ProfileIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  ExercisesIndexLazyRoute,
  IndexIndexLazyRoute,
  ProfileIndexLazyRoute,
])

/* prettier-ignore-end */
